# Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 5001, host: 5001

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip
    pip3 install --upgrade pip
    pip3 install -r /vagrant/requirements.txt
  SHELL

  config.vm.provision "file", source: "./creditcard.csv", destination: "~/creditcard.csv"
  config.vm.provision "file", source: "./fraud_detection_model.py", destination: "~/fraud_detection_model.py"
  config.vm.provision "file", source: "./fraud_detection_model.pkl", destination: "~/fraud_detection_model.pkl"
  config.vm.provision "shell", inline: "python3 ~/fraud_detection_model.py > ~/flask_app.log 2>&1 &", run: "always"
end

